### ISSUE TITLE
get portals working

### ISSUE THREAD

**Issue by okdistribute** [karissa/dps#3]

**Comment by max-mapper** [comment]
## arxiv
- has files http://arxiv.org/src/0905.2326v1/anc "of modest size" allowed
- doesnt have hashes of files
- has gzip of all files available for download
- doesnt have list of all identifiers available through api

## dataverse
- has files (https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/20575) 2gb per file limit
- md5 available but they are phasing it out and replacing with their own special hash called UNF https://github.com/IQSS/UNF/blob/9b51c107743fbd92086184186eb1eed4a33abd4b/src/main/java/org/dataverse/unf/UnfString.java#L35-L37 that is working on sha256 support https://github.com/IQSS/UNF/blob/9b51c107743fbd92086184186eb1eed4a33abd4b/src/main/java/org/dataverse/unf/UnfString.java#L35-L37
- can use search wildcards to potentially get all global_ids: look for "global_id":"doi:10.5072/FK2/CE0052" at http://guides.dataverse.org/en/latest/api/search.html#advanced-search-example ... that's the hdl/doi at the dataset/study level. you could do a wildcard search (q=*) and include only type=dataset to get all the hdl/doi values.

**Comment by pdurbin** [comment]
@maxogden thanks for your interest in Dataverse! I'm curious why you say there's a limit of 2 GB per file. http://dx.doi.org/10.7910/DVN/4XNRE3 has several >50 GB files and http://dx.doi.org/10.7910/DVN/8DRZHU has some large files as well.

**Comment by pdurbin** [comment]
@maxogden you're right that https://dataverse.harvard.edu (now) currently has a per file limit of 2 GB as of https://github.com/IQSS/dataverse/commit/979efca but the Dataverse software itself can be configured to allow larger file sizes. You can see a list of Dataverse installations at http://dataverse.org . I hope this helps! We should probably provide an API you can query to determine these limits per installation before you attempt to upload a file.

**Comment by webmaven** [comment]
Is this issue still active?
